name: Docker Image
on: [push]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --tag cfreak/homepage:latest
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: docker login --username '${{ secrets.DOCKER_HUB_USERNAME }}' --password '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'
      - name: Push Image to Docker Hub
        run: docker push cfreak/homepage:latest
