name: Docker Image
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Publish Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --tag cfreak/homepage:latest
      - name: Login to Docker Hub
        run: docker login --username '${{ secrets.DOCKER_HUB_USERNAME }}' --password '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'
      - name: Push Image to Docker Hub
        run: docker push cfreak/homepage:latest
